{% set version = "22.8.1" %}
{% set hash = "90d74148ed26dc0e1500f368b0b8b4097f792fe7612f402f05db5f01ec534cdf" %}
{% set build_number = "0" %}

package:
  name: conda-libmamba-solver
  version: {{ version }}

source:
  url: https://github.com/conda-incubator/conda-libmamba-solver/archive/refs/tags/{{ version }}.tar.gz
  sha256: {{ hash }}

build:
  skip: true  # [py<37]
  number: {{ build_number }}
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python
    - pip
    - wheel
    - setuptools
    - flit-core >=3.2,<4
  run:
    - python
    - libmambapy >=0.23
    - conda >=4.13
    - importlib_metadata

test:
  imports:
    - conda_libmamba_solver
  commands:
    # - CONDA_SOLVER_LOGIC=libmamba conda create -n test --dry-run scipy  # [not win]  Not crosss platform.
    - conda create --experimental-solver libmamba -n test --dry-run scipy

about:
  home: https://github.com/conda-incubator/conda-libmamba-solver
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'The fast mamba solver, now in conda!'
  dev_url: https://github.com/conda-incubator/conda-libmamba-solver
  doc_url: https://github.com/conda-incubator/conda-libmamba-solver/blob/main/README.md
